import { of } from 'rxjs';

export const DATA = of([
  {
    id: 258,
    created_at: '2023-07-12 16:49:22',
    last_update: '2023-07-13 15:13:55',
    nombreEvaluador: 'LIYIBERTH LOZANO GUERRERO',
    nombreEvaluado: 'CLINICA VALLEDUPAR',
    resultados: [
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 1,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Naturaleza jurídica del escenario de práctica.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 2,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Código REPS',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 3,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Habilitación de los servicios que presta la IPS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 4,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Estructura orgánica del escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Al momento de la visita la persona responsable de docencia servicio no dispone de la información',
        orden: 5,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Registros estadísticos de atenciones por cada servicio habilitado en la Sede Visitada.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'En la página web de la clínica se hizo el rastreo y hay evidencia en la Misión de la vocación docente y/o declaración de compromiso con la gestión del conocimiento',
        orden: 6,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Vocación docente en la plataforma estratégica del escenario.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 3,
        calificacion: 33,
        observacion: 'No existe un presupuesto a la fecha para docencia servicio y/o educación',
        orden: 7,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Evidencias de asignación de recursos para el mantenimiento y fortalecimiento de la relación docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Con calidad se realiza está tarea de acuerdo a los servicios habilitados y se cruza con los lineamientos de asignación de cupos, para definir el número de estudiantes que se pueden recibir por programa académico.',
        orden: 8,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar:
          'Análisis de la capacidad instalada y utilizada para la docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Debe hacerse un inventario de los recursos disponibles para el desarrollo de las prácticas y a la fecha no existe.',
        orden: 9,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar: 'Infraestructura y medios educativos.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Se debe solicitar a la UPC la inclusión del listado de los estudiantes como anexo de la póliza.',
        orden: 10,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Pólizas de responsabilidad civil extracontractual vigentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se debe verificar periódicamente la afiliación del estudiante, una opción podía ser plataforma Adres',
        orden: 11,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Afiliación al Sistema General de Seguridad Social en Salud – SGSSS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Solicitar a las Universidades las constancias de entrega de EPP a los docentes y estudiantes',
        orden: 12,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Elementos de protección personal.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se debe publicar el protocolo de bioseguridad en el espacio web de la inducción',
        orden: 13,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Protocolos de bioseguridad (existencia y aplicación).\r\n',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Se deben dar a conocer o publicar las principales guías en el espacio web',
        orden: 14,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar:
          'Existencia, acceso y aplicación de las guías de práctica clínica y protocolos de Atención',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 15,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Condiciones generales de bienestar en el escenario',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion: 'Se debe publicar en el espacio web de la inducción',
        orden: 16,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Reglamento de prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Se debe publicar en el espacio web de la inducción',
        orden: 17,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Contratos especiales de práctica formativa',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'No Hay acta de constitución',
        orden: 18,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar:
          'Responsables de supervisar las prácticas formativas que se desarrollan en la IPS.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 19,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Comité docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Se debe crear el espacio Drive desde correo institucional de docencia servicio para manejar allí la documentación y plantar mecanismo para su adecuada custodia',
        orden: 20,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Proceso de inducción.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: null,
        orden: 21,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Sistema de información y gestión documental para la docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Verificar que los soportes se encuentren principalmente la convalidación de títulos obtenidos en el exterior',
        orden: 22,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Idoneidad de los profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: 'Gestionar con Andina',
        orden: 23,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Plan de formación continua en temas del desarrollo de la práctica que incluya formación en pedagogía y docencia, para el personal asistencial con funciones Docentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Todos los semestres se deben formalizar los anexos técnicos con cada universidad de acuerdo al número de estudiantes acordados para las prácticas.',
        orden: 24,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Suficiencia de profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Todos los contratos deben tener la contribución a la vocación docente',
        orden: 25,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Función docente incorporada en los contratos y reconocimientos por parte de las IES.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 26,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Registro calificado de los programas que desarrollan prácticas formativas en el escenario (aplica para programas en funcionamiento).',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 27,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Convenios docencia servicio suscritos con las IES para el desarrollo de programas activos y para programas proyectados para desarrollarse en el escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 28,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Plan de prácticas formativas (anexos técnicos).',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Verificar el cumplimiento de los mecanismos de evaluación de las prácticas',
        orden: 29,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Mecanismos de evaluación de las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: null,
        orden: 30,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar: 'Autoevaluación de la relación docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: null,
        orden: 31,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar:
          'Planes de mejoramiento para la relación docencia servicio en el escenario.',
      },
    ],
    tipo_evaluacion: {
      id: 1,
      tipo: 1,
      nombre: 'MATRIZ DE VERIFICACIÓN DE LAS CONDICIONES DE CALIDAD DEL PROCESO',
      descripcion: 'EVALUACIÓN ENTIDAD',
    },
    usuario: {
      id: 12,
      tipo_documento: null,
      numero_documento: null,
      numero_telefono: null,
      rol_id: 1,
      nombre_completo: 'LIYIBERTH LOZANO GUERRERO',
      email: 'liyibethlozano@unicesar.edu.co',
      username: null,
      is_active: 1,
    },
    entidad: {
      id: 201,
      representante_id: null,
      tipo_documento: 1,
      numero_documento: '003',
      tipo_id: 1,
      nombre_completo: 'CLINICA VALLEDUPAR',
      telefono: '003',
      entidad_id: null,
      created_at: '2023-06-22 16:48:51',
      created_by: 12,
      updated_at: null,
      updated_by: null,
      tipo: {
        id: 1,
        nombre: 'ENTIDAD',
      },
      entidad: null,
    },
  },
  {
    id: 262,
    created_at: '2023-07-11 16:31:45',
    last_update: '2023-07-13 17:56:29',
    nombreEvaluador: 'LIYIBERTH LOZANO GUERRERO',
    nombreEvaluado: 'CLINICA MEDICOS ALTA COMPLEJIDAD',
    resultados: [
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 1,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Naturaleza jurídica del escenario de práctica.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 2,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Código REPS',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 3,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Habilitación de los servicios que presta la IPS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 4,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Estructura orgánica del escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 5,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Registros estadísticos de atenciones por cada servicio habilitado en la Sede Visitada.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 6,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Vocación docente en la plataforma estratégica del escenario.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 7,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Evidencias de asignación de recursos para el mantenimiento y fortalecimiento de la relación docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 8,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar:
          'Análisis de la capacidad instalada y utilizada para la docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se hizo la actualización en excel de los medios educativos de los cuales se dispone en la actualidad',
        orden: 9,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar: 'Infraestructura y medios educativos.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 10,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Pólizas de responsabilidad civil extracontractual vigentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 11,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Afiliación al Sistema General de Seguridad Social en Salud – SGSSS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'La UPC no hizo entrega de elementos de protección personal a la clínica y tampoco evidenció entrega a los estudiantes',
        orden: 12,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Elementos de protección personal.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 13,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Protocolos de bioseguridad (existencia y aplicación).\r\n',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 14,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar:
          'Existencia, acceso y aplicación de las guías de práctica clínica y protocolos de Atención',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 15,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Condiciones generales de bienestar en el escenario',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 16,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Reglamento de prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 17,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Contratos especiales de práctica formativa',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 18,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar:
          'Responsables de supervisar las prácticas formativas que se desarrollan en la IPS.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 19,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Comité docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 20,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Proceso de inducción.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 21,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Sistema de información y gestión documental para la docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 22,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Idoneidad de los profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'La clínica ha iniciado trabajo de educación continuada. La UDES compartió su plan de educación con la Andina y UPC no se ha logrado.',
        orden: 23,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Plan de formación continua en temas del desarrollo de la práctica que incluya formación en pedagogía y docencia, para el personal asistencial con funciones Docentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 24,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Suficiencia de profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: null,
        orden: 25,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Función docente incorporada en los contratos y reconocimientos por parte de las IES.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 26,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Registro calificado de los programas que desarrollan prácticas formativas en el escenario (aplica para programas en funcionamiento).',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 27,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Convenios docencia servicio suscritos con las IES para el desarrollo de programas activos y para programas proyectados para desarrollarse en el escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 28,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Plan de prácticas formativas (anexos técnicos).',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 29,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Mecanismos de evaluación de las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 30,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar: 'Autoevaluación de la relación docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 31,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar:
          'Planes de mejoramiento para la relación docencia servicio en el escenario.',
      },
    ],
    tipo_evaluacion: {
      id: 1,
      tipo: 1,
      nombre: 'MATRIZ DE VERIFICACIÓN DE LAS CONDICIONES DE CALIDAD DEL PROCESO',
      descripcion: 'EVALUACIÓN ENTIDAD',
    },
    usuario: {
      id: 12,
      tipo_documento: null,
      numero_documento: null,
      numero_telefono: null,
      rol_id: 1,
      nombre_completo: 'LIYIBERTH LOZANO GUERRERO',
      email: 'liyibethlozano@unicesar.edu.co',
      username: null,
      is_active: 1,
    },
    entidad: {
      id: 206,
      representante_id: null,
      tipo_documento: 1,
      numero_documento: '05',
      tipo_id: 1,
      nombre_completo: 'CLINICA MEDICOS ALTA COMPLEJIDAD',
      telefono: '05',
      entidad_id: null,
      created_at: '2023-07-11 16:31:40',
      created_by: 12,
      updated_at: null,
      updated_by: null,
      tipo: {
        id: 1,
        nombre: 'ENTIDAD',
      },
      entidad: null,
    },
  },
  {
    id: 263,
    created_at: '2023-07-11 16:31:57',
    last_update: '2023-07-13 17:41:32',
    nombreEvaluador: 'LIYIBERTH LOZANO GUERRERO',
    nombreEvaluado: 'CLINICA SANTA ISABEL',
    resultados: [
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion: 'Hace falta actualizar a fecha más reciente',
        orden: 1,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Naturaleza jurídica del escenario de práctica.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: 'Se  dispone del ultimo con fecha de enero que esta vigente hasta agosto 2023',
        orden: 2,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Código REPS',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Existe documento pero se debe Cruzar la información de anexos técnicos con la información publicada en el REPS',
        orden: 3,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Habilitación de los servicios que presta la IPS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Existe en el organigrama la dependencia pero debe internamente darse la descripción del cargo y su designación',
        orden: 4,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Estructura orgánica del escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'No existe el archivo al momento de la autoevaluación',
        orden: 5,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Registros estadísticos de atenciones por cada servicio habilitado en la Sede Visitada.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Talento humano debe hacer el ajuste de la gestión del conocimiento o hacer declaración de la vocación docente para que pueda ser publicado en página web',
        orden: 6,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Vocación docente en la plataforma estratégica del escenario.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Ya hay asignación presupuestal dispuesto para compras de elementos para fortalecer la RDS como casilleros por ejemplo',
        orden: 7,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Evidencias de asignación de recursos para el mantenimiento y fortalecimiento de la relación docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 8,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar:
          'Análisis de la capacidad instalada y utilizada para la docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se cumple pero se debe hacer un informe sobre el uso de los espacios, llevar un registro para cuantificar su uso, por  ejemplo: uso de auditorio y de la biblioteca',
        orden: 9,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar: 'Infraestructura y medios educativos.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'La p+oliza de la UDES tiene en sus anexos especificados los nombres de los beneficiados y los programas. Por parte de la UPC existe la poliza pero hace Falta la relación de los estudiantes beneficiados.',
        orden: 10,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Pólizas de responsabilidad civil extracontractual vigentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 11,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Afiliación al Sistema General de Seguridad Social en Salud – SGSSS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'La UDES entrega oficio donde se evidencia la dotación. Se debe solicitar este mismo oficio a la UPC donde quede la evidencia que se hace entrega de los Elemetos de protección a los estudiantes, ya que la universidad se demora en hacer entrega de insumos',
        orden: 12,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Elementos de protección personal.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: 'Se socializan y queda evidencia de la actividad',
        orden: 13,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Protocolos de bioseguridad (existencia y aplicación).\r\n',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Estudiantes tienen acceso a las guias, se hace la socialización en la inducción, hace falta obtener la trazabilidad, se requere una plataforma por ejemplo ALMERA',
        orden: 14,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar:
          'Existencia, acceso y aplicación de las guías de práctica clínica y protocolos de Atención',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Hay condiciones de bienestar se debe crear un Formato de uso de elementos para evidenciar el prestamo de estos recursos como por ejemplo, uso de computador y de auditorio, uso de casilleros, etc',
        orden: 15,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Condiciones generales de bienestar en el escenario',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 16,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Reglamento de prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Hay certificación de UDES y tambien certificación de la delegación de funciones en la clínica pero hace Falta la certificación de la UPC',
        orden: 17,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Contratos especiales de práctica formativa',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 18,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar:
          'Responsables de supervisar las prácticas formativas que se desarrollan en la IPS.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 19,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Comité docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 20,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Proceso de inducción.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 21,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Sistema de información y gestión documental para la docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Tener en cuenta que ésta información puede ser cambiante de un semestre a otro',
        orden: 22,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Idoneidad de los profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Se debe trabajar en la proyección de un plan de capacitaciones articulado con la UPC que las tematicas beneficien a los colaboradores que son además docentes',
        orden: 23,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Plan de formación continua en temas del desarrollo de la práctica que incluya formación en pedagogía y docencia, para el personal asistencial con funciones Docentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Recordar que siempre se debe verificar los servicios  declarado en el REPS, deben coincidir con los consignados en el Anexo',
        orden: 24,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Suficiencia de profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Pendiente adición de clausulas en los contratos',
        orden: 25,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Función docente incorporada en los contratos y reconocimientos por parte de las IES.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Falta enfermeria UPC',
        orden: 26,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Registro calificado de los programas que desarrollan prácticas formativas en el escenario (aplica para programas en funcionamiento).',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Diligenciar la lista de chequeo para verificar que el convenio cumple con todas las especificaciones del MINISTERIO y del decreto 2376 de 2010',
        orden: 27,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Convenios docencia servicio suscritos con las IES para el desarrollo de programas activos y para programas proyectados para desarrollarse en el escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Realizar trabajo de campo para verificar cumplimiento de la delegación progresiva',
        orden: 28,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Plan de prácticas formativas (anexos técnicos).',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 29,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Mecanismos de evaluación de las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se deben hacer informes de para consolidar los resultados de las autoevaluaciones',
        orden: 30,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar: 'Autoevaluación de la relación docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion: 'Hay que trabajar en el cumplimiento de los planes de mejora',
        orden: 31,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar:
          'Planes de mejoramiento para la relación docencia servicio en el escenario.',
      },
    ],
    tipo_evaluacion: {
      id: 1,
      tipo: 1,
      nombre: 'MATRIZ DE VERIFICACIÓN DE LAS CONDICIONES DE CALIDAD DEL PROCESO',
      descripcion: 'EVALUACIÓN ENTIDAD',
    },
    usuario: {
      id: 12,
      tipo_documento: null,
      numero_documento: null,
      numero_telefono: null,
      rol_id: 1,
      nombre_completo: 'LIYIBERTH LOZANO GUERRERO',
      email: 'liyibethlozano@unicesar.edu.co',
      username: null,
      is_active: 1,
    },
    entidad: {
      id: 204,
      representante_id: null,
      tipo_documento: 1,
      numero_documento: '03',
      tipo_id: 1,
      nombre_completo: 'CLINICA SANTA ISABEL',
      telefono: '03',
      entidad_id: null,
      created_at: '2023-07-11 16:30:34',
      created_by: 12,
      updated_at: null,
      updated_by: null,
      tipo: {
        id: 1,
        nombre: 'ENTIDAD',
      },
      entidad: null,
    },
  },
  {
    id: 264,
    created_at: '2023-07-11 16:32:16',
    last_update: '2023-07-13 17:53:27',
    nombreEvaluador: 'LIYIBERTH LOZANO GUERRERO',
    nombreEvaluado: 'CLINICA MEDICOS CENTRO',
    resultados: [
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 1,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Naturaleza jurídica del escenario de práctica.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 2,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Código REPS',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 3,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Habilitación de los servicios que presta la IPS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 4,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Estructura orgánica del escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 5,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Registros estadísticos de atenciones por cada servicio habilitado en la Sede Visitada.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 6,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Vocación docente en la plataforma estratégica del escenario.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 7,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Evidencias de asignación de recursos para el mantenimiento y fortalecimiento de la relación docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 8,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar:
          'Análisis de la capacidad instalada y utilizada para la docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 9,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar: 'Infraestructura y medios educativos.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 10,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Pólizas de responsabilidad civil extracontractual vigentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 11,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Afiliación al Sistema General de Seguridad Social en Salud – SGSSS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'La UPC no hizo entrega de elementos de protección personal a la clínica y tampoco evidenció entrega a los estudiantes',
        orden: 12,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Elementos de protección personal.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 13,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Protocolos de bioseguridad (existencia y aplicación).\r\n',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 14,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar:
          'Existencia, acceso y aplicación de las guías de práctica clínica y protocolos de Atención',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 15,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Condiciones generales de bienestar en el escenario',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 16,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Reglamento de prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 17,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Contratos especiales de práctica formativa',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 18,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar:
          'Responsables de supervisar las prácticas formativas que se desarrollan en la IPS.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 19,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Comité docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 20,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Proceso de inducción.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 21,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Sistema de información y gestión documental para la docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 22,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Idoneidad de los profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'La clínica ha iniciado trabajo de educación continuada. La UDES compartió su plan de educación con la Andina y UPC no se ha logrado.',
        orden: 23,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Plan de formación continua en temas del desarrollo de la práctica que incluya formación en pedagogía y docencia, para el personal asistencial con funciones Docentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 24,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Suficiencia de profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: null,
        orden: 25,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Función docente incorporada en los contratos y reconocimientos por parte de las IES.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 26,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Registro calificado de los programas que desarrollan prácticas formativas en el escenario (aplica para programas en funcionamiento).',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 27,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Convenios docencia servicio suscritos con las IES para el desarrollo de programas activos y para programas proyectados para desarrollarse en el escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 28,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Plan de prácticas formativas (anexos técnicos).',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 29,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Mecanismos de evaluación de las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 30,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar: 'Autoevaluación de la relación docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 31,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar:
          'Planes de mejoramiento para la relación docencia servicio en el escenario.',
      },
    ],
    tipo_evaluacion: {
      id: 1,
      tipo: 1,
      nombre: 'MATRIZ DE VERIFICACIÓN DE LAS CONDICIONES DE CALIDAD DEL PROCESO',
      descripcion: 'EVALUACIÓN ENTIDAD',
    },
    usuario: {
      id: 12,
      tipo_documento: null,
      numero_documento: null,
      numero_telefono: null,
      rol_id: 1,
      nombre_completo: 'LIYIBERTH LOZANO GUERRERO',
      email: 'liyibethlozano@unicesar.edu.co',
      username: null,
      is_active: 1,
    },
    entidad: {
      id: 205,
      representante_id: null,
      tipo_documento: 1,
      numero_documento: '04',
      tipo_id: 1,
      nombre_completo: 'CLINICA MEDICOS CENTRO',
      telefono: '04',
      entidad_id: null,
      created_at: '2023-07-11 16:31:14',
      created_by: 12,
      updated_at: null,
      updated_by: null,
      tipo: {
        id: 1,
        nombre: 'ENTIDAD',
      },
      entidad: null,
    },
  },
  {
    id: 265,
    created_at: '2023-07-11 16:35:34',
    last_update: '2023-07-13 17:34:58',
    nombreEvaluador: 'LIYIBERTH LOZANO GUERRERO',
    nombreEvaluado: 'CLINICA LAURA DANIELA',
    resultados: [
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 1,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Naturaleza jurídica del escenario de práctica.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: 'Se  dispone del ultimo con fecha de enero que esta vigente hasta agosto 2023',
        orden: 2,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Código REPS',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Existe documento pero se debe Cruzar la información de anexos técnicos con la información publicada en el REPS',
        orden: 3,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Habilitación de los servicios que presta la IPS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Existe en el organigrama la dependencia pero debe internamente darse la descripción del cargo y su designación',
        orden: 4,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Estructura orgánica del escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'No existe el archivo al momento de la autoevaluación',
        orden: 5,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Registros estadísticos de atenciones por cada servicio habilitado en la Sede Visitada.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Talento humano debe hacer el ajuste de la gestión del conocimiento o hacer declaración de la vocación docente para que pueda ser publicado en página web',
        orden: 6,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar: 'Vocación docente en la plataforma estratégica del escenario.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 0,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Ya hay asignación presupuestal dispuesto para compras de elementos para fortalecer la RDS como casilleros por ejemplo',
        orden: 7,
        condicion: 'ASPECTOS GENERALES',
        aspecto_evaluar:
          'Evidencias de asignación de recursos para el mantenimiento y fortalecimiento de la relación docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 8,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar:
          'Análisis de la capacidad instalada y utilizada para la docencia servicio.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se cumple pero se debe hacer un informe sobre el uso de los espacios, llevar un registro para cuantificar su uso, por  ejemplo: uso de auditorio y de la biblioteca',
        orden: 9,
        condicion: 'CAPACIDAD INSTALADA',
        aspecto_evaluar: 'Infraestructura y medios educativos.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'La p+oliza de la UDES tiene en sus anexos especificados los nombres de los beneficiados y los programas. Por parte de la UPC existe la poliza pero hace Falta la relación de los estudiantes beneficiados.',
        orden: 10,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Pólizas de responsabilidad civil extracontractual vigentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 11,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Afiliación al Sistema General de Seguridad Social en Salud – SGSSS.',
      },
      {
        tv_visual: 1,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'La UDES entrega oficio donde se evidencia la dotación. Se debe solicitar este mismo oficio a la UPC donde quede la evidencia que se hace entrega de los Elemetos de protección a los estudiantes, ya que la universidad se demora en hacer entrega de insumos',
        orden: 12,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Elementos de protección personal.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: 'Se socializan y queda evidencia de la actividad',
        orden: 13,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Protocolos de bioseguridad (existencia y aplicación).\r\n',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Estudiantes tienen acceso a las guias, se hace la socialización en la inducción, hace falta obtener la trazabilidad, se requere una plataforma por ejemplo ALMERA',
        orden: 14,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar:
          'Existencia, acceso y aplicación de las guías de práctica clínica y protocolos de Atención',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Hay condiciones de bienestar se debe crear un Formato de uso de elementos para evidenciar el prestamo de estos recursos como por ejemplo, uso de computador y de auditorio, uso de casilleros, etc',
        orden: 15,
        condicion: 'SEGURIDAD, PROTECCIÓN Y BIENESTAR',
        aspecto_evaluar: 'Condiciones generales de bienestar en el escenario',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 16,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Reglamento de prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Hay certificación de UDES y tambien certificación de la delegación de funciones en la clínica pero hace Falta la certificación de la UPC',
        orden: 17,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Contratos especiales de práctica formativa',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 18,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar:
          'Responsables de supervisar las prácticas formativas que se desarrollan en la IPS.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 19,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Comité docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 20,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Proceso de inducción.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 21,
        condicion: 'ORGANIZACIÓN ADMINISTRATIVA PARA LA DOCENCIA SERVICIO',
        aspecto_evaluar: 'Sistema de información y gestión documental para la docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Tener en cuenta que ésta información puede ser cambiante de un semestre a otro',
        orden: 22,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Idoneidad de los profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Se debe trabajar en la proyección de un plan de capacitaciones articulado con la UPC que las tematicas beneficien a los colaboradores que son además docentes',
        orden: 23,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Plan de formación continua en temas del desarrollo de la práctica que incluya formación en pedagogía y docencia, para el personal asistencial con funciones Docentes.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Recordar que siempre se debe verificar los servicios  declarado en el REPS, deben coincidir con los consignados en el Anexo',
        orden: 24,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar: 'Suficiencia de profesores para las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Pendiente adición de clausulas en los contratos',
        orden: 25,
        condicion: 'PERSONAL DOCENTE',
        aspecto_evaluar:
          'Función docente incorporada en los contratos y reconocimientos por parte de las IES.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion: 'Falta enfermeria UPC',
        orden: 26,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Registro calificado de los programas que desarrollan prácticas formativas en el escenario (aplica para programas en funcionamiento).',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 3,
        calificacion: 33,
        observacion:
          'Diligenciar la lista de chequeo para verificar que el convenio cumple con todas las especificaciones del MINISTERIO y del decreto 2376 de 2010',
        orden: 27,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar:
          'Convenios docencia servicio suscritos con las IES para el desarrollo de programas activos y para programas proyectados para desarrollarse en el escenario.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 2,
        calificacion: 67,
        observacion:
          'Realizar trabajo de campo para verificar cumplimiento de la delegación progresiva',
        orden: 28,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Plan de prácticas formativas (anexos técnicos).',
      },
      {
        tv_visual: 1,
        tv_documental: 0,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: null,
        orden: 29,
        condicion: 'PRÁCTICAS FORMATIVAS',
        aspecto_evaluar: 'Mecanismos de evaluación de las prácticas formativas.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion:
          'Se deben hacer informes de para consolidar los resultados de las autoevaluaciones',
        orden: 30,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar: 'Autoevaluación de la relación docencia servicio.',
      },
      {
        tv_visual: 0,
        tv_documental: 1,
        tv_entrevista: 1,
        val_cond: 1,
        calificacion: 100,
        observacion: 'Hay que trabajar en el cumplimiento de los planes de mejora',
        orden: 31,
        condicion: 'CULTURA DEL MEJORAMIENTO CONTINUO',
        aspecto_evaluar:
          'Planes de mejoramiento para la relación docencia servicio en el escenario.',
      },
    ],
    tipo_evaluacion: {
      id: 1,
      tipo: 1,
      nombre: 'MATRIZ DE VERIFICACIÓN DE LAS CONDICIONES DE CALIDAD DEL PROCESO',
      descripcion: 'EVALUACIÓN ENTIDAD',
    },
    usuario: {
      id: 12,
      tipo_documento: null,
      numero_documento: null,
      numero_telefono: null,
      rol_id: 1,
      nombre_completo: 'LIYIBERTH LOZANO GUERRERO',
      email: 'liyibethlozano@unicesar.edu.co',
      username: null,
      is_active: 1,
    },
    entidad: {
      id: 203,
      representante_id: null,
      tipo_documento: 1,
      numero_documento: '02',
      tipo_id: 1,
      nombre_completo: 'CLINICA LAURA DANIELA',
      telefono: '02',
      entidad_id: null,
      created_at: '2023-07-11 16:30:10',
      created_by: 12,
      updated_at: null,
      updated_by: null,
      tipo: {
        id: 1,
        nombre: 'ENTIDAD',
      },
      entidad: null,
    },
  },
]);
